version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: codetest
      POSTGRES_PASSWORD: pass
    volumes:
      - ./people_places.sql:/docker-entrypoint-initdb.d/people_places.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: codetest
      POSTGRES_PASSWORD: pass
    depends_on:
      - db
    volumes:
      - ./data:/data
